title: SYB's Homepage
page-top-title: Welcome to SYB's Homepage
top-section-bg-text: 心如止水，攻无不克
home-subtitle: YueBing SONG &ensp;|&ensp;"Mooncake"
copyright-text: '&copy; SYB 2025-2026. All Rights Reserved.'
